### PR TITLE
exponential cone via ECOS

### PR DESCRIPTION
**Pull request by AxelBreuer**
Add Exponential cones via ECOS (See https://github.com/cvxpy/cvxpy/issues/1915)

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]
LGTM assuming all tests pass.

**Comment by SteveDiamond** [comment]
Hmm the tests don't pass. I assume they pass locally for you?

**Comment by AxelBreuer** [comment]
Indeed test_expcone() from diffcp/tests/test_ecos.py is working well on my side (I just re-ran it on my laptop).
Below some information of my python setup under windows 10 pro:
python 3.9.13
cvxpy==1.2.2
ecos==2.0.10
numpy==1.23.4
osqp==0.6.2.post5
pytest==7.2.0
qdldl==0.1.5.post2
scipy==1.9.3
scs==3.2.2
**What ECOS version do you have on your side ?**

**Comment by SteveDiamond** [comment]
Looks like ecos 2.0.7post in the failing builds and 2.0.10 in the passing builds. Could you try changing this line https://github.com/cvxgrp/diffcp/blob/1a8d7e51fc4450abe1834c3effe8c215f534690a/setup.py#L105
to specify ecos >= 2.0.10?

**Comment by SteveDiamond** [comment]
Ok that didn't work. I will try and fix it for you, not 100% sure what will work.

**Comment by SteveDiamond** [comment]
@AxelBreuer thanks for doing this! I fixed the CI and merged it in. I am going to release a new version on pypi, though running into some issues at the moment.

**Comment by SteveDiamond** [comment]
Up on pypi now.

**Comment by AxelBreuer** [comment]
Again, thank you very much @SteveDiamond for your advice and your reactivness !

**Pull request merged**
