### PR TITLE
Use GitHub Actions & Pytest

### PR DESCRIPTION
**Pull request by phschiele**
Hi @akshayka !
this PR addresses #43 and #44. It also switches from `nose` to `pytest`, I hope that's fine with you.

Some remaining open points:

- [x] GitHub Actions do not seem to be enabled
- [x] `test_threading` fails under ubuntu & Python 3.6 (under nose and pytest, relative tolerance is `1e-7`, maximum relative difference is `1e-5`)
- [x] Potentially one could specify lower versions for scipy and numpy during the install, but the `scipy=1.3 numpy=1.16` combo from cvxpy did not work.
- [x] I have commented out some conditions to see if everything works as expected, needs to be reverted before merge
- [x] The secrets need to be added to the repo

### CODE REVIEW

**Comment by akshayka** [comment]
Thanks @phschiele!

- The repository settings say that all Github Actions are enabled. What kind of error are you running into?
- I'm fine with decreasing the tolerance so that `test_threading` passes.
- Can you clarify what error you ran when specifying the scipy and numpy versions?
- I have added the PYPI secrets to the repository.

**Comment by phschiele** [comment]
@akshayka 
- if it's not the settings, then I am not quite sure why the action is not running. Perhaps adding the first action from a forked repo PR does not trigger them yet? As you can see [here](https://github.com/phschiele/diffcp/actions/runs/919672674), the checks run in my fork. We can check this if you add the "cleanup" action posted below to `.github/workflows/build.yml`.
- Regarding numpy/scipy versions: Initially, I tried with `numpy=1.15 scipy=1.1.0` as per `setup.py`. This raised conda dependency conflicts. In the last commit, I have fixed the versions in alignment with cvxpy.

```yml
name: build

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
```

**Comment by phschiele** [comment]
@sbarratt Yes, the idea is to run the build incl. tests on every PR. Building wheels and deploying to PYPI will only be done whenever a new tag is created.

**Review by akshayka — APPROVED** [review]
LGTM, modulo the workflows not running. Will look into that ...

**Comment by akshayka** [comment]
> @akshayka
> 
> * if it's not the settings, then I am not quite sure why the action is not running. Perhaps adding the first action from a forked repo PR does not trigger them yet? 

That appears to be the case:

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

However, the documentation says that I should see an option to approve your workflow and run it on this PR, which I do not. (I approved the PR to see if the option would show up.) All I see is the following

image


These links might be helpful:

https://github.com/WordPress/gutenberg/issues/17324#issuecomment-724784917

https://github.com/WordPress/gutenberg/pull/26876

**Comment by phschiele** [comment]
@akshayka The GH Actions are running (and passing) now.

**Comment by akshayka** [comment]
Looks good, thanks @phschiele!

**Pull request merged**
