### PR TITLE
fixed pybind11 error

### PR DESCRIPTION
**Pull request by sbarratt**
a la https://github.com/pybind/python_example/issues/32

### CODE REVIEW

**Comment by akshayka** [comment]
That's really weird. The bug you reported in https://github.com/cvxgrp/diffcp/issues/15 isn't 'Module not found', but it's that pybind11 can't find Eigen. We saw this bug earlier because eigen wasn't included in the source distribution, but I've fixed that & installation from pip just works for me now. The change in this PR shouldn't fix not being able to find Eigen headers.

**Comment by sbarratt** [comment]
It’s because we include pybind11/eigen first. I suspect that if we put
pybind11/pybind11 first, well have the same issue.

**Comment by akshayka** [comment]
Are you installing from the test repo or from pypi? Can you try installing the latest version (1.0.6) from pypi in a fresh environment and posting the entire error message?

**Comment by akshayka** [comment]
Okay, never mind my previous post, will merge.

**Pull request merged**
